//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlinanDersler
    {
        public int Id { get; set; }
        public int Ogretmen_id { get; set; }
        public int Ogrenci_id { get; set; }
        public int Ders_id { get; set; }
    
        public virtual tblDers tblDers { get; set; }
        public virtual tblOgrenci tblOgrenci { get; set; }
        public virtual tblOgretmen tblOgretmen { get; set; }
    }
}
