//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDers()
        {
            this.tblAlinanDersler = new HashSet<tblAlinanDersler>();
            this.tblNotlar = new HashSet<tblNotlar>();
            this.tblVerilenDersler = new HashSet<tblVerilenDersler>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Aciklama { get; set; }
        public string Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAlinanDersler> tblAlinanDersler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNotlar> tblNotlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVerilenDersler> tblVerilenDersler { get; set; }
    }
}
